stages:
  - deploy

trigger-store-build:
  stage: deploy
  only:
    - pushes
    - web
    - api
  script:
    - curl --location --request POST https://gitlab.com/api/v4/projects/16103315/trigger/pipeline --form 'token=$CI_JOB_TOKEN' --form 'ref=master'
